/**
 * AlgoLens — Core Type Definitions
 *
 * Shared types for the LeetCode problem analysis pipeline.
 * Used across API routes, components, and Supabase interactions.
 */

/** Difficulty tier of a LeetCode problem */
export type Difficulty = 'Easy' | 'Medium' | 'Hard';

/**
 * The structured blueprint returned by the LLM analysis.
 * Every field is required — the LLM system prompt enforces strict JSON.
 */
export interface AnalysisResult {
  /** Problem difficulty classification */
  difficulty: Difficulty;

  /** Algorithmic topic tags (e.g., "Two Pointers", "Dynamic Programming") */
  tags: string[];

  /** The core algorithmic pattern identified (e.g., "Sliding Window") */
  pattern: string;

  /** Big-O time complexity with explanation */
  timeComplexity: string;

  /** Big-O space complexity with explanation */
  spaceComplexity: string;

  /** Step-by-step strategic approach (NOT code — conceptual steps) */
  strategySteps: string[];

  /** Critical edge cases to consider */
  edgeCases: string[];
}

/**
 * The Supabase row shape for persisted analyses.
 * Extends AnalysisResult with database-managed fields.
 */
export interface SupabaseAnalysisRecord extends AnalysisResult {
  /** UUID primary key (auto-generated by Supabase) */
  id: string;

  /** ISO 8601 timestamp of creation */
  created_at: string;

  /** The raw problem text that was analyzed */
  problem_text: string;
}

/**
 * Props for the AnalyzerInput component.
 */
export interface AnalyzerInputProps {
  /** Callback fired when the user submits problem text */
  onAnalyze: (problemText: string) => void;

  /** Whether an analysis is currently in progress */
  isLoading: boolean;
}

/**
 * Props for the BlueprintView component.
 */
export interface BlueprintViewProps {
  /** The structured analysis result to display */
  result: AnalysisResult;

  /** Callback to reset and analyze a new problem */
  onReset: () => void;
}

/**
 * Shape of the POST body sent to /api/analyze
 */
export interface AnalyzeRequestBody {
  problemText: string;
}

/**
 * Shape of a successful /api/analyze response
 */
export interface AnalyzeSuccessResponse {
  success: true;
  data: AnalysisResult;
}

/**
 * Shape of an error /api/analyze response
 */
export interface AnalyzeErrorResponse {
  success: false;
  error: string;
}

export type AnalyzeResponse = AnalyzeSuccessResponse | AnalyzeErrorResponse;
